# Generated by Django 5.1.3 on 2025-06-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uvaq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinformation',
            name='institutional_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='identification',
            name='curp',
            field=models.CharField(blank=True, db_index=True, max_length=18, null=True, unique=True),
        ),
    ]
